import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>One Good Thing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>One Good Thing</h1>
          <p>Recording all the good you do, every day.</p>
          <div>Login to get started</div>
        </div>
        <div>
          <h2>Good board</h2>
          <p>Get inspiration from all the good that others have done</p>
          <ul>
            <li>good thing </li>
          </ul>
        </div>
      </main>
    </>
  )
}
