import Head from 'next/head'
import Link from 'next/link'
import React from 'react'
import { useUser, useSupabaseClient } from '@supabase/auth-helpers-react'

export default function Layout({ children }: any) {
  const supabase = useSupabaseClient()
  const user = useUser()
  console.log('user', user)
  return (
    <>
      <Head>
        <title>One Good Thing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-4xl mx-auto mt-24">
        <div className="flex item-center justify-between mb-12">
          <h1 className="flex items-center gap-2">
            <span className="rounded-full w-4 h-4 bg-orange-500"></span>
            <Link href="/">One Good Thing</Link>
          </h1>
          <div>
            {user ? (
              <p className="text-xs">
                <span className="font-serif italic">{user.email}</span>
              </p>
            ) : (
              <Link href="/login"> Login to get started</Link>
            )}
          </div>
        </div>
        {children}
      </main>
    </>
  )
}
