import Head from 'next/head'
import Link from 'next/link'
import React from 'react'

export default function Layout({ children }: any) {
  return (
    <>
      <Head>
        <title>One Good Thing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-4xl mx-auto mt-24 ">
        <div className="flex item-center justify-between">
          <h1>One Good Thing</h1>
          <div>
            <Link href="/login"> Login to get started</Link>
          </div>
        </div>
        {children}
      </main>
    </>
  )
}
