import Head from 'next/head'
import Link from 'next/link'
import React from 'react'
import { useUser, useSupabaseClient } from '@supabase/auth-helpers-react'

export default function Layout({ children }: any) {
  const supabase = useSupabaseClient()
  const user = useUser()

  return (
    <>
      <Head>
        <title>One Good Thing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-4xl mx-auto mt-24">
        <div className="flex item-center justify-between mb-12">
          <h1>
            <Link href="/">One Good Thing</Link>
          </h1>
          <div>{user ? 'Welcome' : <Link href="/login"> Login to get started</Link>}</div>
        </div>
        {children}
      </main>
    </>
  )
}
